pypro/aperitivos/urls.py
from django.urls import path

from pypro.aperitivos.views import video, indice

app_name = "aperitivos"

urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice'),
]

pypro/base/urls.py
from django.urls import path

from pypro.base.views import home

app_name = "base"

urlpatterns = [
    path('', home, name='home'),
]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.contrib import auth
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.hashers import make_password


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

    def with_perm(self, perm, is_active=True, include_superusers=True, backend=None, obj=None):
        if backend is None:
            backends = auth._get_backends(return_tuples=True)
            if len(backends) == 1:
                backend, _ = backends[0]
            else:
                raise ValueError(
                    'You have multiple authentication backends configured and '
                    'therefore must provide the `backend` argument.'
                )
        elif not isinstance(backend, str):
            raise TypeError(
                'backend must be a dotted import path string (got %r).'
                % backend
            )
        else:
            backend = auth.load_backend(backend)
        if hasattr(backend, 'with_perm'):
            return backend.with_perm(
                perm,
                is_active=is_active,
                include_superusers=include_superusers,
                obj=obj,
            )
        return self.none()


class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.
    Username and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/aperitivos/views.py
from django.shortcuts import render
from django.urls import reverse


class Video:
    def __init__(self, slug, titulo, youtube_id) -> None:
        self.slug = slug
        self.titulo = titulo

    def get_absolut_url(self):
        return reverse('aperitivos:video', args=(self.slug,))


videos = [
    Video('01', 'Café com Analytics: 01', 'McQ-DttWgwU'),
    Video('02', 'Café com Analytics: 02', 'vD8C541oT4k')
    ]

videos_dct = {v.slug: v for v in videos}


def indice(request):
    return render(request, 'aperitivos/indice.html', context={'videos': videos})


def video(request, slug):
    video = videos_dct[slug]
    return render(request, 'aperitivos/video.html', context={'video': video})

pypro/base/views.py
# from django.http import HttpResponse
from django.shortcuts import render
# Create your views here.


def home(request):
    return render(request, 'base/home.html')

pypro/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Aperitivo{% endblock title %}
{% block description %}Página com todos os vídeos{% endblock description %}
{% block body %}

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <h1 class="mt-4 mb-3">Lista de vídeos</h1>
        <ol>
          {% for video in videos %}
            <li><a href="{{ video.get_absolut_url }}">{{ video.titulo | default:"Faltando título" }}</a></li>
          {% empty %}
            <li>Não foi encontrado nenhum vídeo.</li>
          {% endfor %}
        </ol>
      </div>
    </div>
  </div>

{% endblock body %}

pypro/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Aperitivo{% endblock title %}
{% block description %}Página com vídeo{% endblock description %}
{% block body %}

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <h1 class="mt-4 mb-3">{{ video.titulo | default:"Faltando título" }}</h1>
        <iframe id="ytplayer" type="text/html" width="640" height="360"
          src="http://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" />
      </div>
    </div>
  </div>

{% endblock body %}

pypro/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}Python Pro{% endblock title %}</title>

  <meta name="description" content={% block description %}"Página do Curso Python Pro"{% endblock description %}>
  <meta name="author" content="Gustavo Suto, aluno do Renzo Nuccitelli">

  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/scripts.js' %}"></script>

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
      </div>
    </div>
  </nav>

{% block body %}{% endblock body %}

<footer class="main-footer mt-5 pt-4 text-light">
  <div class="container">
    <div class="row">
      <div class="col">
        <h3>Entre em contato</h3>
        <address>
          +55 11 9999-99999
          <br/>
          <a href="mailto:ramalho@gmail.com" class="text-light">Email para o professor</a>
        </address>
      </div>
    </div>
  </div>
  <div class="rights pb-3">  
    <div class="container">
    <div class="row">
      <div class="col">
        {% now 'Y' %} Python Pro - Todos os direitos reservados.
      </div>
    </div>
  </div>
</div>

</footer>

</body>

</html>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Home{% endblock title %}
{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">

      <div class="jumbotron">
        <h2>
          Curso de Python da Python Pro =)
        </h2>
        <p>
          Em breve, mais informações. \o/
          <a href="https://novatec.com.br/livros/pythonfluente/" target="_blank">Python Fluente</a>
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <h5 class="card-header">
          Mais detalhes sobre o professor
        </h5>
        <div class="card-body">
          <p class="card-text">
            <img src="{% static 'img/LucianoRamalho.jpg' %}" class="img-thumbnail float-left mr-3"
              alt="Foto de Luciano Ramalho." width="150" /> O que segue é minha mini-bio de programador. Programo por
            hobby desde 1978 e por profissão desde 1982. Fundei a Hiperlógica, primeira empresa brasileira dedicada
            inteiramente ao Zope e Python (nunca usamos outro servidor de aplicações nem outra linguagem, exceto em
            scripts de integração com sistemas legados). Continuo inteiramente focado nestas tecnologias, ultimamente
            com ênfase em Django. Fui diretor técnico do BrasilOnline (BOL) na Abril S/A, desde sua concepção em 1994
            até um pouco antes do Sr. Roberto Civita entregar o ouro ao nosso principal concorrente a troco de nada
            (acho que ele não "estava a fim" dessa tal de Web). Naquela época, aprendi a respeitar o software livre e a
            simplicidade como princípio de engenharia de software. Python é livre e simples.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}